import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";

import Footer from "./components/Footer";
import NavBar from "./components/NavBar";

const lexend = Lexend({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "John Mignelli | Chiropractor",
    template: "%s | John Mignelli",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lexend.variable}>
      <body className="flex flex-col">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
